### PR TITLE
chore: clean go.mod

### PR DESCRIPTION
**Pull request by robert-zaremba**
## Description

Removed not used dependencies.

----

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added appropriate labels to the PR
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by adamewozniak** [comment]
@robert-zaremba I think this was handled by #28, except for the go version update

**Comment by robert-zaremba** [comment]
now we have conflict. we should have more responsiveness on reviews. I will update this PR

**Review by adamewozniak — APPROVED** [review]
lgtm if we get tests to pass - I've gotten `Error: ../../../go/pkg/mod/github.com/osmosis-labs/osmosis@v1.0.4/x/gamm/types/expected_keepers.go:55:29: undefined: exported.SupplyI` before when updating the SDK locally

**Comment by robert-zaremba** [comment]
Strange, this PR doesn't update osmosis. How possible this error doesn't exist in `main`?

**Pull request merged**
